// HACER UNA CLASE FURGONETA QUE EXTIENDA DE VEHICULO
// HACER UNA CLASE COCHE QUE EXTIENDA DE VEHICULO

// VEHICULO TIENE UNAS PROPIEDADES POR DEFECTO: PUERTAS 5, PESO 3000 KG
// FURGONETA SUSTITUYE EL PESO A 5000 KG
// COCHE SUSTITUYE EL PESO A 3500 KG Y AÑADE UN CAMPO RADIO(TRUE / FALSE)
// FURGONETA ADEMÁS AÑADE EXTRA UN COLOR Y UN TIPO QUE PUEDE SER ESPECIAL O NO (TRUE / FALSE)
